### ISSUE TITLE
[Bug] Support stamping on yq rule not working when stamp coming from running a "non-mocked" workspace_status script

### ISSUE THREAD

**Issue by opicaud** [aspect-build/bazel-lib#463]
Hi guys, 
Big thanks for this feature very vey useful!!

I've tried it and i have an issue that i replicate [here](https://github.com/opicaud/bazel-lib) with a red test when running
`bazel test --config=release //lib/tests/yq/...`
It's unfortunately not working when i stamp a value from stable-status.txt when I use the release config with bazel.
For info i am running on Bazel 5.4.0

_Originally posted by @opicaud in https://github.com/aspect-build/bazel-lib/issues/223#issuecomment-1603183000_

**Comment by malt3** [comment]
Hey. Thanks for raising this issue. I can reproduce your bug.

It turns out when I first implemented this, I used a newer version of yq on my host when finding a working yq expression to read the stamping info from the volatile and stable info files.

This seems to be broken with any yq version older than 4.30.3. Since the yq version in this ruleset is held back to 4.25.2, it is broken by default.

To reproduce, you can use this expression:

yq 'load_str(filename) | split("\n")' bazel-out/stable-status.txt  

Output on yq >= 4.30.3:

```
yq 'load_str(filename) | split("\n")' bazel-out/stable-status.txt  
- BUILD_EMBED_LABEL v1.2.3
- BUILD_HOST x1mp
- BUILD_USER malte
- STABLE_BUILD_FROM_WORKSPACE_STATUS_SCRIPT from_workspace_status_script
- STABLE_BUILD_SCM_LOCAL_CHANGES dirty
- STABLE_BUILD_SCM_SHA d53869af5c7c199bc7288b9884a884828f6ea5af
- STABLE_BUILD_SCM_TAG v1.32.1-15-gd53869a
- ""
```

Output on older versions:

```
yq 'load_str(filename) | split("\n")' bazel-out/stable-status.txt  
- |
  BUILD_EMBED_LABEL v1.2.3
  BUILD_HOST x1mp
  BUILD_USER malte
  STABLE_BUILD_FROM_WORKSPACE_STATUS_SCRIPT from_workspace_status_script
  STABLE_BUILD_SCM_LOCAL_CHANGES dirty
  STABLE_BUILD_SCM_SHA d53869af5c7c199bc7288b9884a884828f6ea5af
  STABLE_BUILD_SCM_TAG v1.32.1-15-gd53869a
```

I'm currently trying to find an expression that works also on older yq versions.
