### ISSUE TITLE
[FR]: instructions to register jq toolchain in MODULE.bazel

### ISSUE THREAD

**Issue by pdeva** [aspect-build/bazel-lib#592]
### What is the current behavior?

the release page only shows examples of registering jq toolchain with workspace file. 

### Describe the feature

currently no such instructions exist

**Comment by alexeagle** [comment]
There are no such instructions because there's nothing to do, our MODULE.bazel file already registers jq_toolchain for you.

See #597 for some related refactoring, but this will still be true.

We should probably add a sentence in the install section there about the toolchains being registered by default.
